# Model selection for generation
generation_model: gpt-4o

# Input/Output paths
input:
  tasks_filename: all_tasks_n.csv
  raw_tasks_dir: ${paths.raw_dir}/tasks
  synth_dir: ${paths.synth_dir}

output:
  dir: ${paths.results_dir}

# Generation parameters
generation:
  num_correct_answers: 3
  num_partial_answers: 3
  num_incorrect_answers: 3
  mode: per_question # single | per_question | all
  chain_of_thought: false
  cache: true

  # Control what information is passed to generators
  pass_reference_answer_for:
    correct: true
    partial: true
    incorrect: false

# LM settings
lm:
  temp_generation: 1.0
  cache: true
