model:
  base: qwen3:0.6b
  cache: true
  temperature: 0.6
  max_tokens: 4096

  with_prompt: true
  pass_reference: true
  pass_reference_answer: false


dataset:
  csv_train: data/gras/train.csv
  csv_test: data/gras/test.csv

  n_train_examples: null # if null use all
  n_test_examples: null # if null use all

evaluation:
  manual: false


output:
  dir: ${paths.output_dir}/few_shot

hyperparameters:
  num_candidate_programs: 4
  num_threads: 4
  num_bootstrapped_demos: 4
  num_labeled_demos: 4